name: Auto Test

on:
  workflow_dispatch:

jobs:
  auto-test:
    runs-on: ubuntu-20.04
    steps:
    - run: git clone https://github.com/louislam/uptime-kuma.git .
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm i
    - run: npm i vite -g
    - run: npm run build
    - run: npm test
      env:
        HEADLESS_TEST: 1
